import React, { useState } from 'react';
import { officialCoverage } from '../data/officialCoverage';
import { fullMathematicsStages, fullElectricalStages, fullEsasStages } from '../data/curriculumData';
import { termBank } from '../data/termBank';
import { ArrowRight, BookOpen, Layers3, Target } from 'lucide-react';
const stageMap={mathematics:fullMathematicsStages,esas:fullEsasStages,electrical:fullElectricalStages};
interface Props { completedToday:number; dailyTarget:number; totalSolved:number; onNavigate:(tab:'curriculum'|'terms'|'drill')=>void; }
export function StudyPlan({completedToday,dailyTarget,totalSolved,onNavigate}:Props) {
  const [completed]=useState<Set<string>>(()=>{try{return new Set(JSON.parse(localStorage.getItem('ree_completed_lessons')||'[]'))}catch{return new Set()}});
  const [termScores]=useState<Record<string,{level:number}>>(()=>{try{return JSON.parse(localStorage.getItem('ree_terms_v1')||'{}')}catch{return {}}});
  const priorities=officialCoverage.flatMap(subject=>subject.topics.map(topic=>({subject,topic,done:topic.lessons.filter(id=>completed.has(id)).length,score:topic.items*(1-topic.lessons.filter(id=>completed.has(id)).length/topic.lessons.length)}))).sort((a,b)=>b.score-a.score).slice(0,5);
  const known=termBank.filter(t=>(termScores[t.id]?.level||0)>=2).length;
  return <div className="plan-page"><header className="plan-hero"><span className="review-eyebrow">A PLAN BUILT FROM THE PRC MAP</span><h1>Study what moves you forward.</h1><p>Use the official item allocation to decide where to spend time. A completed lesson means you studied it; mastery still needs recall and practice.</p></header>
    <div className="plan-metrics"><button onClick={()=>onNavigate('curriculum')}><BookOpen size={19}/><strong>{[...completed].length}</strong><span>lessons studied</span><ArrowRight size={14}/></button><button onClick={()=>onNavigate('terms')}><Layers3 size={19}/><strong>{known}<small>/{termBank.length}</small></strong><span>terms recalled twice</span><ArrowRight size={14}/></button><button onClick={()=>onNavigate('drill')}><Target size={19}/><strong>{completedToday}<small>/{dailyTarget}</small></strong><span>questions today · {totalSolved} overall</span><ArrowRight size={14}/></button></div>
    <div className="plan-grid"><section><div className="section-label"><span>SUBJECT WEIGHTS</span><span>Official REE exam</span></div><div className="plan-weight-chart">{officialCoverage.map(s=><div key={s.track} className={`weight-${s.track}`} style={{flex:s.weight}}><strong>{s.weight}%</strong><small>{s.track==='mathematics'?'Mathematics':s.track==='esas'?'ESAS':'Electrical'}</small></div>)}</div><p>Each subject has 100 blueprint items. The percentages above describe the subject weight in the full exam.</p><div className="section-label plan-gap-title"><span>YOUR LESSON PROGRESS</span></div>{officialCoverage.map(s=>{const lessons=stageMap[s.track].flatMap(stage=>stage.lessons);const done=lessons.filter(l=>completed.has(l.id)).length;return <div className="plan-subject" key={s.track}><div><strong>{s.name}</strong><span>{done}/{lessons.length}</span></div><div className="review-meter"><i style={{width:`${done/lessons.length*100}%`}}/></div></div>})}</section>
    <section><div className="section-label"><span>NEXT STUDY BLOCKS</span><span>Items × unstudied lessons</span></div><p className="plan-subtitle">Start with higher allocation groups that have more starter lessons left.</p>{priorities.map((p,i)=><div className="plan-priority" key={p.topic.id}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{p.topic.title}</strong><small>{p.subject.name} · {p.topic.items} items per 100 · {p.done}/{p.topic.lessons.length} lessons studied</small></div></div>)}<div className="plan-next"><button onClick={()=>onNavigate('curriculum')}>Choose a lesson <ArrowRight size={14}/></button><button onClick={()=>onNavigate('terms')}>Review terms <ArrowRight size={14}/></button></div></section></div>
  </div>;
}
